// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgndwpkbhtoylgphhhzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnbmR3cGtiaHRveWxncGhoaHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDU4MTYsImV4cCI6MjA2NzcyMTgxNn0.YP0ImWGr_uEWQwgnguUN7kuIW6_JWdT07xTIft7jNcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});